"""AI-assisted rule authoring — draft rules, then gate them through verification.

Policy: nothing generated by AI is added to a book unverified. Each candidate
must pass BOTH gates (``verify.verify_rule``) and is credited to the author
who ran the generation (``--author``), with ``source: ai-generated``.
"""

from __future__ import annotations

import json
import re

from ..model import ModelClient
from .defs import RuleDefinition, dedupe_rules
from .verify import VerificationResult, stamp, verify_rule

LANG_PREFIX = {
    "python": "PY", "javascript": "JS", "sql": "SQL", "swift": "SW", "go": "GO",
    "java": "JAVA", "kotlin": "KT", "ruby": "RB", "terraform": "TF", "dockerfile": "DK",
}

_SYSTEM = (
    "You are a senior security rule-author. Produce NEW detection rules for the "
    "given language and topic, at the level of a 30-year industry veteran. "
    "Return STRICT JSON only: a list of objects, each with: "
    "description, severity (info|low|medium|high|critical), category, "
    "regex (a python re pattern that matches a BAD line), message, fix (the safe "
    "alternative), vulnerable_example (1 BAD line), safe_example (1 GOOD line). "
    "Rules must be line-based, low-false-positive, and distinct from each other."
)


def _parse_candidates(raw: str) -> list[dict]:
    m = re.search(r"\[[\s\S]*\]", raw)
    if not m:
        return []
    try:
        data = json.loads(m.group(0))
    except Exception:
        return []
    return data if isinstance(data, list) else []


def prefix_for(language: str) -> str:
    return LANG_PREFIX.get(language, language.upper()[:2].upper())


def drafts_from_response(language: str, raw: str, existing_ids: set[str],
                         author: str, start_at: int = 1) -> list[RuleDefinition]:
    """Turn the LLM's JSON draft into RuleDefinitions (never verified yet)."""
    prefix = prefix_for(language)
    rules: list[RuleDefinition] = []
    n = start_at
    for item in _parse_candidates(raw):
        if not isinstance(item, dict) or not item.get("regex"):
            continue
        rid = item.get("id") or f"{prefix}-{n:03d}"
        while rid in existing_ids:
            n += 1
            rid = f"{prefix}-{n:03d}"
        existing_ids.add(rid)
        n += 1
        rules.append(
            RuleDefinition(
                id=rid,
                language=language,
                description=str(item.get("description", "")).strip(),
                severity=str(item.get("severity", "low")).lower(),
                regex=str(item.get("regex", "")),
                message=str(item.get("message", "")),
                fix=str(item.get("fix", "")),
                category=str(item.get("category", "best-practice")),
                author=author,
                source="ai-generated",
                vulnerable_example=str(item.get("vulnerable_example", "")),
                safe_example=str(item.get("safe_example", "")),
            )
        )
    return rules


def generate_verified(model: ModelClient, language: str, topic: str, author: str,
                      max_rules: int = 10) -> tuple[list[RuleDefinition], list[VerificationResult]]:
    """Draft rules via the model, then run the two-gate verification on every one.

    Returns (verified_rules, all_results) — unverified candidates are discarded,
    with their results preserved so the CLI can show why.
    """
    prompt = (
        f"Language: {language}\nTopic: {topic}\n"
        f"Generate up to {max_rules} rules. All must be NEW (not generic). "
        "Be concrete and precise."
    )
    raw = model.chat(_SYSTEM, prompt)
    candidates = drafts_from_response(language, raw, set(), author)
    verified, results = [], []
    for rule in candidates:
        res = verify_rule(rule, model)
        results.append(res)
        if res.verified:
            verified.append(stamp(rule, res))
    return dedupe_rules(verified), results